<?php
function displayLaplace() {
    $str = "<form method='post' action='index.php?cat=analysis&subcat=processLaplace' accept-charset='utf-8'>"
            . "<p><input type=\"radio\" name=\"functionName\" value=\"calculateLaplaceLocal\" "
            . "alt=\"Расчитать вероятность используя Локальную Теорему Лапласа\" checked> "
            . "<b>" . CONST_LAPLACE_LOCAL . ".</b><br />"
            . "Если вероятность P появления случайного события A в каждом испытании "
            . "постоянна, то вероятность P<sub>n</sub>(m) того, что в n испытаниях событие А "
            . "наступит ровно m раз, приближенно равна: "
            . "P<sub>n</sub>(m) ≈ 1 / √npq * 1 / √2π * е<sup>-x<sup>2</sup>/2</sup>, где "
            . "x = (m - np) / √npq.</p>"
            . "<p><input type=\"radio\" name=\"functionName\" value=\"calculateLaplaceIntegral\" "
            . "alt=\"Расчитать вероятность используя Интегральную Теорему Лапласа\"> "
            . "<b>" . CONST_LAPLACE_INTEGRAL . ".</b><br />"
            . "Если вероятность P появления случайного события A в каждом испытании, то "
            . "вероятность P<sub>n</sub>(m<sub>1</sub> ≤ m ≤ m<sub>2</sub>) того, что в n "
            . "испытаниях событие А наступит не менее m<sub>1</sub> и не более m<sub>2</sub> раз "
            . "(от m<sub>1</sub> до m<sub>2</sub> раз включительно), приближенно равна: "
            . "P<sub>n</sub>(m<sub>1</sub> ≤ m ≤ m<sub>2</sub>) ≈ Ф(x<sub>2</sub>) - Ф(x<sub>1</sub>), "
            . "где Ф(x) = 1 / √2π * ∫е<sup>-z<sup>2</sup>/2</sup>dz, x<sub>2</sub> = (m<sub>2</sub> - np) "
            . "/ √npq, x<sub>1</sub> = (m<sub>1</sub> - np) / √npq "
            . "</p>"
            . "<p><input type=\"radio\" name=\"functionName\" value=\"calculateLaplaceDeviation\" "
            . "alt=\"Расчитать вероятность отклонения относительной частоты от вероятности по Лапласу\"> "
            . "<b>" . CONST_LAPLACE_DEVIATION . ".</b><br />"
            . "Вероятность того, что в n независимых испытаниях относительная частота ω=m/n "
            . "события A отклонится от вероятности P (появления данного события в каждом "
            . "испытании) не более чем на ε, приблизительно равна: "
            . "P(|m / n - p| ≤ ε) ≈ 2Ф(ε√n / √pq), "
            . "где Ф(х) = 1 / √2π * ∫е<sup>-z<sup>2</sup>/2</sup>dz - функция Лапласа."
            . "</p>";
    
    $str .= "<p>Рассчитываем вероятность для игр, в которых было угадано: "
            . "<select name='opt'>"
            . "<option value='All' selected>All</option>"
            . "<option value='6x'>6x</option>"
            . "<option value='5x'>5x</option>"
            . "<option value='4x'>4x</option>"
            . "<option value='3x'>3x</option>"
            . "</select>"
            . " номеров в "
            . "<input type='text' name='draws' size='5' value='100'>"
            . " играх для лототрона "
            . "<select name='drawmachine'>"
            . "<option value='All' selected>All</option>"
            . "<option value='А'>А</option>"
            . "<option value='Б'>Б</option>"
            . "</select>"
            . " и набора шаров "
            . "<select name='setofballs'>"
            . "<option value='All' selected>All</option>"
            . "<option value='1'>1</option>"
            . "<option value='2'>2</option>"
            . "<option value='3'>3</option>"
            . "<option value='4'>4</option>"
            . ". "
            . "<input type='submit' value='show'>"
            . "</p>"
            . "</form>";
    
    return $str;
}